openapi: 3.0.3
info:
  title: NuuMee Admin Panel API
  description: Internal admin API for NuuMee operations management
  version: 1.0.0

servers:
  - url: https://nuumee-api-1084586894518.us-central1.run.app/api/v1
    description: Production
  - url: http://localhost:8000/api/v1
    description: Local development

security:
  - AdminPassword: []

components:
  securitySchemes:
    AdminPassword:
      type: apiKey
      in: header
      name: X-Admin-Password
      description: Admin password for authentication

  schemas:
    # ==================== Common ====================
    PaginatedResponse:
      type: object
      properties:
        items:
          type: array
          items: {}
        total:
          type: integer
          description: Total number of items
        page:
          type: integer
          description: Current page (1-indexed)
        pages:
          type: integer
          description: Total number of pages
        per_page:
          type: integer
          description: Items per page
      required: [items, total, page, pages, per_page]

    ErrorResponse:
      type: object
      properties:
        detail:
          type: string
          description: Error message
      required: [detail]

    # ==================== User ====================
    AdminUserSummary:
      type: object
      description: User summary for list view
      properties:
        uid:
          type: string
        email:
          type: string
        display_name:
          type: string
          nullable: true
        tier:
          type: string
          enum: [free, pro, business]
        credits:
          type: integer
        created_at:
          type: string
          format: date-time
        last_active:
          type: string
          format: date-time
          nullable: true
        jobs_count:
          type: integer
          description: Total jobs created
      required: [uid, email, tier, credits, created_at]

    AdminUserDetail:
      type: object
      description: Full user detail with recent activity
      allOf:
        - $ref: '#/components/schemas/AdminUserSummary'
        - type: object
          properties:
            subscription:
              $ref: '#/components/schemas/SubscriptionInfo'
              nullable: true
            recent_jobs:
              type: array
              items:
                $ref: '#/components/schemas/AdminJobSummary'
              maxItems: 10
            recent_transactions:
              type: array
              items:
                $ref: '#/components/schemas/CreditTransaction'
              maxItems: 10
            photo_url:
              type: string
              nullable: true

    SubscriptionInfo:
      type: object
      properties:
        id:
          type: string
        status:
          type: string
          enum: [active, canceled, past_due, trialing]
        plan:
          type: string
        current_period_end:
          type: string
          format: date-time
      required: [id, status, plan, current_period_end]

    CreditTransaction:
      type: object
      properties:
        id:
          type: string
        type:
          type: string
          enum: [purchase, usage, admin_adjustment, promo, referral, subscription]
        amount:
          type: integer
          description: Positive for credit, negative for debit
        balance_after:
          type: integer
        description:
          type: string
        created_at:
          type: string
          format: date-time
      required: [id, type, amount, balance_after, created_at]

    CreditAdjustmentRequest:
      type: object
      properties:
        amount:
          type: integer
          description: Amount to add (positive) or deduct (negative). Max 2000.
          minimum: -2000
          maximum: 2000
        reason:
          type: string
          description: Reason for adjustment
          maxLength: 500
      required: [amount]

    CreditAdjustmentResponse:
      type: object
      properties:
        success:
          type: boolean
        new_balance:
          type: integer
        transaction_id:
          type: string
      required: [success, new_balance, transaction_id]

    # ==================== Job ====================
    JobStatus:
      type: string
      enum: [pending, processing, completed, failed, cancelled]

    JobType:
      type: string
      enum: [video_generation, subtitles, watermark]

    AdminJobSummary:
      type: object
      properties:
        id:
          type: string
        user_id:
          type: string
        user_email:
          type: string
        type:
          $ref: '#/components/schemas/JobType'
        status:
          $ref: '#/components/schemas/JobStatus'
        credits_used:
          type: integer
        created_at:
          type: string
          format: date-time
        completed_at:
          type: string
          format: date-time
          nullable: true
        error_message:
          type: string
          nullable: true
          description: Short error message for list view
      required: [id, user_id, status, created_at]

    AdminJobDetail:
      type: object
      allOf:
        - $ref: '#/components/schemas/AdminJobSummary'
        - type: object
          properties:
            input_path:
              type: string
              nullable: true
            output_path:
              type: string
              nullable: true
            error_details:
              type: string
              nullable: true
              description: Full error message and stack trace
            metadata:
              type: object
              additionalProperties: true
              description: Job-specific metadata

    JobRetryRequest:
      type: object
      properties:
        note:
          type: string
          description: Optional note for audit
          maxLength: 500

    JobRetryResponse:
      type: object
      properties:
        success:
          type: boolean
        job_id:
          type: string
        new_status:
          type: string
      required: [success, job_id, new_status]

    # ==================== Payments ====================
    PaymentStats:
      type: object
      properties:
        mrr:
          type: number
          format: float
          description: Monthly Recurring Revenue in dollars
        total_revenue:
          type: number
          format: float
          description: All-time revenue in dollars
        subscriber_count:
          type: integer
          description: Active subscribers
        credits_purchased_today:
          type: integer
        credits_purchased_this_month:
          type: integer
      required: [mrr, total_revenue, subscriber_count]

    PaymentTransaction:
      type: object
      properties:
        id:
          type: string
        user_id:
          type: string
        user_email:
          type: string
        type:
          type: string
          enum: [subscription, credit_purchase, refund]
        amount:
          type: number
          format: float
          description: Amount in dollars
        status:
          type: string
          enum: [succeeded, pending, failed, refunded]
        created_at:
          type: string
          format: date-time
      required: [id, type, amount, status, created_at]

    PaymentsResponse:
      type: object
      properties:
        stats:
          $ref: '#/components/schemas/PaymentStats'
        recent_transactions:
          type: array
          items:
            $ref: '#/components/schemas/PaymentTransaction'
          maxItems: 50
      required: [stats, recent_transactions]

    # ==================== Promo Codes ====================
    PromoCode:
      type: object
      properties:
        id:
          type: string
        code:
          type: string
          description: Unique promo code (uppercase)
        credits:
          type: integer
          description: Credits to give
        max_uses:
          type: integer
          nullable: true
          description: null = unlimited
        current_uses:
          type: integer
        expires_at:
          type: string
          format: date-time
          nullable: true
        active:
          type: boolean
        created_at:
          type: string
          format: date-time
      required: [id, code, credits, current_uses, active, created_at]

    CreatePromoRequest:
      type: object
      properties:
        code:
          type: string
          description: Custom promo code (will be uppercased)
          pattern: '^[A-Za-z0-9_-]+$'
          minLength: 3
          maxLength: 30
        credits:
          type: integer
          description: Credits to give
          minimum: 1
          maximum: 10000
        max_uses:
          type: integer
          nullable: true
          description: null = unlimited
          minimum: 1
        expires_at:
          type: string
          format: date-time
          nullable: true
      required: [code, credits]

    # ==================== Dashboard Stats ====================
    DashboardStats:
      type: object
      properties:
        users:
          type: object
          properties:
            total:
              type: integer
            new_today:
              type: integer
            new_this_week:
              type: integer
          required: [total, new_today]
        jobs:
          type: object
          properties:
            total:
              type: integer
            today:
              type: integer
            failed:
              type: integer
              description: Failed jobs needing attention
            processing:
              type: integer
          required: [total, today, failed, processing]
        revenue:
          type: object
          properties:
            this_month:
              type: number
              format: float
            mrr:
              type: number
              format: float
          required: [this_month, mrr]
        promos:
          type: object
          properties:
            active:
              type: integer
            total_redemptions:
              type: integer
          required: [active, total_redemptions]
      required: [users, jobs, revenue, promos]

    # ==================== Health ====================
    HealthResponse:
      type: object
      properties:
        status:
          type: string
          enum: [healthy]
        admin:
          type: boolean
          description: Confirms admin auth is valid
        timestamp:
          type: string
          format: date-time
      required: [status, admin, timestamp]

paths:
  # ==================== Health ====================
  /admin/health:
    get:
      summary: Admin health check
      description: Verify admin authentication and API health
      operationId: adminHealth
      tags: [Health]
      responses:
        '200':
          description: Admin API is healthy
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/HealthResponse'
        '401':
          description: Invalid admin password
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'

  # ==================== Dashboard ====================
  /admin/stats:
    get:
      summary: Get dashboard statistics
      description: Aggregate KPIs for admin dashboard
      operationId: getAdminStats
      tags: [Dashboard]
      responses:
        '200':
          description: Dashboard statistics
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/DashboardStats'
        '401':
          description: Invalid admin password

  # ==================== Users ====================
  /admin/users:
    get:
      summary: List users
      description: Paginated list of users with search
      operationId: listAdminUsers
      tags: [Users]
      parameters:
        - name: page
          in: query
          schema:
            type: integer
            default: 1
            minimum: 1
        - name: per_page
          in: query
          schema:
            type: integer
            default: 25
            minimum: 1
            maximum: 100
        - name: search
          in: query
          description: Search by email, display_name, or uid (prefix match)
          schema:
            type: string
      responses:
        '200':
          description: Paginated list of users
          content:
            application/json:
              schema:
                allOf:
                  - $ref: '#/components/schemas/PaginatedResponse'
                  - type: object
                    properties:
                      items:
                        type: array
                        items:
                          $ref: '#/components/schemas/AdminUserSummary'

  /admin/users/{uid}:
    get:
      summary: Get user details
      description: Full user details with recent jobs and transactions
      operationId: getAdminUser
      tags: [Users]
      parameters:
        - name: uid
          in: path
          required: true
          schema:
            type: string
      responses:
        '200':
          description: User details
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/AdminUserDetail'
        '404':
          description: User not found

  /admin/users/{uid}/credits:
    post:
      summary: Adjust user credits
      description: Add or deduct credits from user account (max 2000)
      operationId: adjustUserCredits
      tags: [Users]
      parameters:
        - name: uid
          in: path
          required: true
          schema:
            type: string
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/CreditAdjustmentRequest'
      responses:
        '200':
          description: Credits adjusted successfully
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/CreditAdjustmentResponse'
        '400':
          description: Invalid amount or insufficient credits
        '404':
          description: User not found

  # ==================== Jobs ====================
  /admin/jobs:
    get:
      summary: List jobs
      description: Paginated list of jobs with status filter
      operationId: listAdminJobs
      tags: [Jobs]
      parameters:
        - name: page
          in: query
          schema:
            type: integer
            default: 1
        - name: per_page
          in: query
          schema:
            type: integer
            default: 25
            maximum: 100
        - name: status
          in: query
          schema:
            $ref: '#/components/schemas/JobStatus'
        - name: user_id
          in: query
          description: Filter by user
          schema:
            type: string
      responses:
        '200':
          description: Paginated list of jobs
          content:
            application/json:
              schema:
                allOf:
                  - $ref: '#/components/schemas/PaginatedResponse'
                  - type: object
                    properties:
                      items:
                        type: array
                        items:
                          $ref: '#/components/schemas/AdminJobSummary'

  /admin/jobs/{job_id}:
    get:
      summary: Get job details
      description: Full job details including error information
      operationId: getAdminJob
      tags: [Jobs]
      parameters:
        - name: job_id
          in: path
          required: true
          schema:
            type: string
      responses:
        '200':
          description: Job details
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/AdminJobDetail'
        '404':
          description: Job not found

  /admin/jobs/{job_id}/retry:
    post:
      summary: Retry failed job
      description: Reset job to pending and re-enqueue (uses already-charged credits)
      operationId: retryAdminJob
      tags: [Jobs]
      parameters:
        - name: job_id
          in: path
          required: true
          schema:
            type: string
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/JobRetryRequest'
      responses:
        '200':
          description: Job retry initiated
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/JobRetryResponse'
        '400':
          description: Job cannot be retried (not failed)
        '404':
          description: Job not found

  # ==================== Payments ====================
  /admin/payments:
    get:
      summary: Get payment analytics
      description: Revenue stats and recent transactions
      operationId: getAdminPayments
      tags: [Payments]
      parameters:
        - name: limit
          in: query
          description: Number of recent transactions
          schema:
            type: integer
            default: 50
            maximum: 100
      responses:
        '200':
          description: Payment analytics
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/PaymentsResponse'

  # ==================== Promo Codes ====================
  /admin/promos:
    get:
      summary: List promo codes
      description: All promo codes (active and inactive)
      operationId: listAdminPromos
      tags: [Promo Codes]
      responses:
        '200':
          description: List of promo codes
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/PromoCode'

    post:
      summary: Create promo code
      description: Create a new promo code
      operationId: createAdminPromo
      tags: [Promo Codes]
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/CreatePromoRequest'
      responses:
        '201':
          description: Promo code created
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/PromoCode'
        '400':
          description: Invalid promo code or code already exists

  /admin/promos/{promo_id}:
    delete:
      summary: Delete promo code
      description: Deactivate a promo code (soft delete)
      operationId: deleteAdminPromo
      tags: [Promo Codes]
      parameters:
        - name: promo_id
          in: path
          required: true
          schema:
            type: string
      responses:
        '200':
          description: Promo code deactivated
          content:
            application/json:
              schema:
                type: object
                properties:
                  success:
                    type: boolean
                  message:
                    type: string
        '404':
          description: Promo code not found

tags:
  - name: Health
    description: API health and authentication verification
  - name: Dashboard
    description: Aggregate statistics for admin dashboard
  - name: Users
    description: User management operations
  - name: Jobs
    description: Job monitoring and retry operations
  - name: Payments
    description: Payment analytics from Stripe
  - name: Promo Codes
    description: Promotional code management
